extern volatile unsigned char temp_modbus_glb;
extern volatile unsigned int modbus_data_array_index_glb;
extern unsigned char my_address_glb;
extern unsigned volatile int modbus_array_index_glb;
extern unsigned char modbus_receive_enable_flag_glb;
extern unsigned volatile int time_count_mdbus_glb;
extern volatile unsigned int receive_data_index_glb;
extern unsigned char modbus_array_glb[];
extern volatile unsigned char i_am_fine_flag_glb;
extern volatile unsigned char CRC_valid_flag_glb;
extern volatile unsigned int timer1_counter, RS485_data_receive_cnt;
extern volatile unsigned char timer2_counter;
extern volatile unsigned char sec_counter;
extern volatile unsigned char AA_count_valid_flag_glb;
extern volatile unsigned char data_reception_complete_flag_glb;
extern volatile unsigned char assign_slave_address_flag_glb;
extern volatile unsigned char continuity_test_pass_flag_glb;
extern volatile unsigned char continuity_test_fail_flag_glb;
extern volatile unsigned char ir_test_pass_flag_glb;
extern volatile unsigned char ir_test_fail_flag_glb;
extern volatile unsigned char withstand_test_pass_flag_glb;
extern volatile unsigned char withstand_test_fail_flag_glb;
extern volatile unsigned char ack_valid_flag_glb;
extern unsigned char analyse_flag;
extern unsigned char temp_global;
extern unsigned char store_result_glb[];
extern unsigned int read_data;
extern float monitor_voltage_glb;
extern float IR_Measure_Voltage_glb;
extern float read_voltage_glb;
extern float Volts_glb[];
extern float ir_result_arr[];
extern unsigned int voltage_integer_part;
extern unsigned int voltage_fractional_part;
extern unsigned int hv_voltage_glb;
extern unsigned int insulation_resistance_glb;
extern unsigned int hv_withstand_time_glb;
extern unsigned char gen_settings_ram[];
extern unsigned char test_settings_ram[];
extern unsigned char prg_specific_setting_ram[];
extern unsigned char hv_msb_glb;
extern unsigned char hv_lsb_glb;
extern unsigned int selected_hv_voltage_glb;
extern volatile unsigned char byte_received_flag;//sets in reception isr after every byte is received in U2RXREG,made false in learn.c where there is reception.(PHTM_1_0.c,Learn.c,ISR.c)
extern volatile int timecount;//this is incremented at every isr,unless cleared externally in other functon.used to count time i.e.for each count t=50ms.(PHTM_1_0.c,Power_On_Status.c,ISR.c)
extern volatile unsigned int ByteReceived;//this register is used to collect a data byte received from U2RXREG through rs232.(Learn.c,ISR.c).
extern unsigned char volume_level_global;
extern volatile unsigned char key_pressed_flag;
extern unsigned char key_data_glb;
extern unsigned char byte_glb;
extern volatile unsigned char key_code;//current
extern unsigned char* disp_start_ptr;
extern unsigned char cards;
extern unsigned char self_test_pass_flag;
extern unsigned char digit_ram[];
extern unsigned char current_cable_number;
extern unsigned int  current_prg_local;
extern unsigned int ir_last_ckt_no_glb;
extern unsigned int last_ckt_no_glb;
extern unsigned char top_position;
extern unsigned char menu_counter;
extern unsigned char arrow_position;
extern unsigned char arrow_pos_global;
extern unsigned char cursor_position_global;
extern volatile unsigned char state_code;
extern unsigned int input_resistance_value_y1;
extern unsigned int input_resistance_value_y2;
extern unsigned int measured_resistance_x1;
extern unsigned int measured_resistance_x2;
extern unsigned int input_resistance_value;
extern volatile unsigned char calibrate_flag_glb;
extern volatile unsigned char last_ckt_number_flag;
extern volatile unsigned char self_test_flag;
extern volatile unsigned char digital_IP_flag_1;
extern volatile unsigned char fail_bin_data;
extern unsigned char print_data[];
extern unsigned char label_data[];
extern volatile unsigned int serial_number_count;
extern unsigned char fct_array[];
extern unsigned char operator_code_1[],operator_code_2[];
extern unsigned char first_shift_hh_glb,second_shift_hh_glb,third_shift_hh_glb,first_shift_mm_glb,second_shift_mm_glb,third_shift_mm_glb;
extern unsigned char first_shift_character_glb,second_shift_character_glb,third_shift_character_glb;
extern unsigned char temp_char_glb;//11_10_18_1.
extern unsigned char srl_isr_glb_index;
extern unsigned char digit_ram_1[];
extern volatile unsigned int receive_label_data_glb;
extern unsigned char serial_number_searched_flag_glb;//21_06_19.
extern unsigned int withstand_last_ckt_no_glb;
extern unsigned int withstand_hv_voltage_glb;
extern unsigned int withstand_current_glb;
extern volatile unsigned char combine_test_flag_glb;
